version: "3.8"
services:
  webtesting:
    container_name: webtesting
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    command: ["tail", "-f", "/dev/null"]
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: .
        target: /webtesting
    restart: "always"
