version: "3.8"
services:
  webtesting:
    container_name: webtesting
    build:
      context: .
      dockerfile: Dockerfile
    command: ["tail", "-f", "/dev/null"]
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: .
        target: /webtesting
    restart: "always"
